[platformio]
src_dir = firmware
; Set default environment to build when clicking the checkmark
default_envs = master

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4

[env:master]
; Only compile the wifi_master_esp32_nonWEBUI folder
build_src_filter = -<*> +<wifi_master_esp32_nonWEBUI/>

[env:master_html]
; Only compile the wifi_master_esp32_WEBUI folder
build_src_filter = -<*> +<wifi_master_esp32_WEBUI/>

[env:slave]
; Only compile the wifi_slave folder
build_src_filter = -<*> +<wifi_slave/>
board_build.f_cpu = 80000000L
; PlatformIO will automatically download this library for the slave
lib_deps =
  ${env.lib_deps}
  smougenot/TM1637

[env:slave_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.f_cpu = 80000000L
build_src_filter = -<*> +<wifi_slave_c3/>
lib_deps =
  ${env.lib_deps}
  smougenot/TM1637

[env:slave8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<wifi_slave_8266/>
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  smougenot/TM1637
